### ISSUE TITLE
non-conformant data contracts (json rpc v.1)

### ISSUE THREAD

**Issue by bytelabsco** [alexanderkozlenko/json-rpc-client#117]
Hello,

First and foremost, thank you for this library.  It's obvious a lot of time and thought went into it.

I need to interface with an API that's serving up non-conformant data contracts.  I'm guessing their implementation is version 1, but only because there's no version mentioned at all in their documentation.  When I try to make calls using this library, I'm getting errors from both the serialization process (if I pass a dictionary holding the parameters I need to pass) and the deserialization process (when passing no values, just to see if I could get a response).

Is there anyway to override this behavior, and specify both the json rpc "envelope" and the parameters/results being returned so they properly serialize/deserialize?

**Comment by alexanderkozlenko** [comment]
Hello @bytelabsco,

Thank you for reaching out regarding the issue. I'm not sure I understand what is the root cause of errors in this case. Could you please provide errors (messages + call stacks), the data which you try to serialize/deserialize, and some example source code used to do these operations?

**Comment by bytelabsco** [comment]
Thanks for the quick reply.  The request and response look like this (tested to be working in Insomnia):

````
// Request
{
  "method": "exec",
  "params": [
    {
      "data": {
        "password": "my-password",
        "user": "my-username"
      },
      "url": "/login/user"
    }
  ],
  "id": 1
}
````

````
// Response
{
  "id": 1,
  "result": [
    {
      "status": {
        "code": 0,
        "message": "OK"
      },
      "url": "/login/user"
    }
  ],
  "session": "<!-- session token -->"
}
````

Then all subsequent requests need the session property on them as a property of the root object.  Even though this example has an integer for the id, you can literally pass anything, and it will work.  I've tried it with a Guid, and it works.

Here's sample code for how I'm trying to call the API

````
var jsonRpcClient= new JsonRpcClient(apiEndpoint, Anemonis.JsonRpc.JsonRpcCompatibilityLevel.Level1);

var parameters = new Dictionary<string, object>();

parameters.Add("data", new LoginRequest
{
    User = "my-username",
    Password = "my-password"
});

parameters.Add("url", "/login/user");

var result = await jsonRpcClient.InvokeAsync<LoginResponse>("exec", parameters);
````
````
    public class LoginRequest
    {
        public string User { get; set; }

        public string Password { get; set; }
    }
````
````
    public class LoginResponse
    {
        public LoginResponseStatus Status { get; set; }

        public string Url { get; set; }
    }
````
````
    public class LoginResponseStatus
    {
        public int Code { get; set; }

        public string Message { get; set; }
    }
````

**Comment by alexanderkozlenko** [comment]
- The `session` property is defined at the root of a JSON-RPC message. Working with additional data at this level of a message is not defined by the JSON-RPC specifications and is not possible using the library.
- According to the example, the result of `exec` JSON-RPC method invocation should be an array of `LoginResponse`e.
- I presume there should be JSON property name mappings defined on CLR types (e.g., CLR `User` to JSON `user`).

It looks like JSON-RPC 1.0, since a successful response in the example does not contain the `error` property with `null` value.

Could you please show what exact exceptions you get?

**Comment by bytelabsco** [comment]
Thanks again for the quick reply.  The limitation for not allowing something outside of the JSON-RPC spec is understandable, but unfortunately will force me into a different direction as I don't have control over the JSON-RPC API I'm interfacing with.  I appreciate the time you put into this conversation, and am happy to provide additional details for the exception(s) I was getting on serialization/deserialization if you think it will help future users, but for my needs you can consider this issue closed.
